### ISSUE TITLE
Fix for Python 3.9.0/1 does not work with typing_extensions 3.7.4.

### ISSUE THREAD

**Issue by kmonson** [ilevkivskyi/typing_inspect#81]
The current version of typing_inspect supports typing_extensions 3.7.4. Running on Python 3.9.0/1 with that version of typing_extensions will result in the following error:

```
venv/lib/python3.9/site-packages/typing_inspect.py:17: in <module>
    from typing_extensions import _TypedDictMeta as _TypedDictMeta_TE
E   ImportError: cannot import name '_TypedDictMeta' from 'typing_extensions'
```

The problem stems from typing_extensions 3.7.4 lacking the required Python < 3.9.2 fixes.

**Comment by ilevkivskyi** [comment]
Yeah, this is a known problem. I think one of the open PRs should address this.
